//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportyFY.Model.SportyEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsMaster
    {
        public NewsMaster()
        {
            this.NewsRatings = new HashSet<NewsRating>();
            this.NewsTags = new HashSet<NewsTag>();
        }
    
        public System.Guid NewsId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
        public string NewsAuthor { get; set; }
        public Nullable<System.DateTime> NewsCreateDate { get; set; }
        public Nullable<System.Guid> NewsRatingId { get; set; }
        public Nullable<System.Guid> NewsTagId { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.Guid> Userid { get; set; }
    
        public virtual ICollection<NewsRating> NewsRatings { get; set; }
        public virtual ICollection<NewsTag> NewsTags { get; set; }
        public virtual NewsSubCategoryMaster NewsSubCategoryMaster { get; set; }
    }
}
