//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportyFY.Model.SportyEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsRating
    {
        public int RatingId { get; set; }
        public System.Guid NewsId { get; set; }
        public Nullable<System.Guid> Userid { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual NewsMaster NewsMaster { get; set; }
    }
}
