//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportyFY.EDM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public System.Guid UserId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string company { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string pincode { get; set; }
        public string status { get; set; }
        public Nullable<bool> isMailsent { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
